PRAGMA foreign_keys = ON;

INSERT INTO items (sku, name, category, unit, has_size, useful_life_days, min_stock, is_active)
VALUES
(NULL, 'RESPIRADOR', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CARTUCHO P/POLVO -P 100', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CARTUCHO P/GASES -6003', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'ADAPTADOR DE FILTRO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CASCO DE SEGURIDAD NARANJA', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CASCO DE SEGURIDAD BLANCO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CASCO DE SEGURIDAD AZUL', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'TAFILETE', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CORTAVIENTO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'BARBIQUEJO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'PROTECTOR AUDITIVO (TAPÓN)', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'PROTECTOR AUDITIVO (OREJERA)', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'LENTES DE SEGURIDAD CLAROS', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'LENTES DE SEGURIDAD OSCUROS', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CLIP O ADAPTADOR DE VISOR', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'VISOR PARA PROTECTOR FACIAL', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'GUANTES DE JEBE', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'GUANTES NITRILO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'GUANTES ANTICORTE', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'GUANTES DE BADANA', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'GUANTES CUERO AMARILLO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'DISPENSADOR / BLOQUEADOR', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'GUANTES CUERO REFORZADO', 'EPP', 'UND', 0, NULL, 0, 1),

(NULL, 'CAMISA CON CINTA REFLECTIVA T/S', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'CAMISA CON CINTA REFLECTIVA T/M', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'CAMISA CON CINTA REFLECTIVA T/L', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'CAMISA CON CINTA REFLECTIVA T/XL', 'EPP', 'UND', 1, NULL, 0, 1),

(NULL, 'PANTALÓN CON CINTA REFLECTIVA T/S', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'PANTALÓN CON CINTA REFLECTIVA T/M', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'PANTALÓN CON CINTA REFLECTIVA T/L', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'PANTALÓN CON CINTA REFLECTIVA T/XL', 'EPP', 'UND', 1, NULL, 0, 1),

(NULL, 'CHOMPA JORGE CHAVEZ T/S', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'CHOMPA JORGE CHAVEZ T/M', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'CHOMPA JORGE CHAVEZ T/L', 'EPP', 'UND', 1, NULL, 0, 1),

(NULL, 'APROM DE CUERO', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'TRAJE TYVEK', 'EPP', 'UND', 0, NULL, 0, 1),
(NULL, 'CAPOTÍN/ROPA PARA AGUA', 'EPP', 'UND', 0, NULL, 0, 1),

(NULL, 'ZAPATO DE SEGURIDAD  T/37', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/38', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/39', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/40', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/41', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/42', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/43', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'ZAPATO DE SEGURIDAD T/44', 'EPP', 'UND', 1, NULL, 0, 1),

(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/37', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/38', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/39', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/40', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/41', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/42', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/43', 'EPP', 'UND', 1, NULL, 0, 1),
(NULL, 'BOTAS DE JEBE PUNTA DE ACERO T/44', 'EPP', 'UND', 1, NULL, 0, 1)

ON CONFLICT(name) DO UPDATE SET
  is_active = 1;
